from . import datasets
from . import losses
from . import market1501_test
from . import market1501_trainval
from . import model
from . import resnet
from . import scores
from . import triplet_loss
from . import utils